// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type ApiKey struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	ApiKeyValue    []byte
	Salt           []byte
	ExpirationTime time.Time
	CreatedAt      time.Time
}

type Cookie struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	CookieValue    string
	Salt           []byte
	ExpirationTime time.Time
	CreatedAt      time.Time
}

type Token struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	TokenValue     []byte
	Salt           []byte
	ExpirationTime time.Time
	CreatedAt      time.Time
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash []byte
	Salt         []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
